/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "D:\\Project\\siteUpdate\\node_modules\\@vuepress\\core\\lib\\client\\components\\GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-4413c380",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4413c380").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-2e00af06",
    path: "/guide/deploy.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2e00af06").then(next)
    },
  },
  {
    name: "v-5f19a21c",
    path: "/guide/redis-sentry.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5f19a21c").then(next)
    },
  },
  {
    name: "v-de38b564",
    path: "/guide/prepare.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-de38b564").then(next)
    },
  },
  {
    name: "v-fbf75a2a",
    path: "/guide/userManual/login.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-fbf75a2a").then(next)
    },
  },
  {
    name: "v-2b64abca",
    path: "/guide/userManual/introduction.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2b64abca").then(next)
    },
  },
  {
    name: "v-db287be4",
    path: "/miscellaneous/release-notes.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-db287be4").then(next)
    },
  },
  {
    name: "v-fb41d53a",
    path: "/zh/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-fb41d53a").then(next)
    },
  },
  {
    path: "/zh/index.html",
    redirect: "/zh/"
  },
  {
    name: "v-f8650914",
    path: "/zh/faq/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-f8650914").then(next)
    },
  },
  {
    path: "/zh/faq/index.html",
    redirect: "/zh/faq/"
  },
  {
    name: "v-0c63e776",
    path: "/zh/guide/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0c63e776").then(next)
    },
  },
  {
    path: "/zh/guide/index.html",
    redirect: "/zh/guide/"
  },
  {
    name: "v-500d679f",
    path: "/faq/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-500d679f").then(next)
    },
  },
  {
    path: "/faq/index.html",
    redirect: "/faq/"
  },
  {
    name: "v-df02e68a",
    path: "/zh/guide/prepare.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-df02e68a").then(next)
    },
  },
  {
    name: "v-5ef88155",
    path: "/zh/guide/redis-sentry.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5ef88155").then(next)
    },
  },
  {
    name: "v-3a7998c8",
    path: "/zh/guide/userManual/login.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3a7998c8").then(next)
    },
  },
  {
    name: "v-7151808c",
    path: "/zh/guide/userManual/introduction.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7151808c").then(next)
    },
  },
  {
    name: "v-685691d3",
    path: "/guide/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-685691d3").then(next)
    },
  },
  {
    path: "/guide/index.html",
    redirect: "/guide/"
  },
  {
    name: "v-46eab6af",
    path: "/zh/miscellaneous/release-notes.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-46eab6af").then(next)
    },
  },
  {
    name: "v-9412f956",
    path: "/zh/guide/deploy.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-9412f956").then(next)
    },
  },
  {
    name: "v-51b4d8ce",
    path: "/guide/run.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-51b4d8ce").then(next)
    },
  },
  {
    name: "v-531b1e33",
    path: "/zh/guide/run.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-531b1e33").then(next)
    },
  },
  {
    path: '*',
    component: GlobalLayout
  }
]