/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "D:\\Project\\siteUpdate\\node_modules\\@vuepress\\core\\lib\\client\\components\\GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-4413c380",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4413c380").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-500d679f",
    path: "/faq/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-500d679f").then(next)
    },
  },
  {
    path: "/faq/index.html",
    redirect: "/faq/"
  },
  {
    name: "v-685691d3",
    path: "/guide/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-685691d3").then(next)
    },
  },
  {
    path: "/guide/index.html",
    redirect: "/guide/"
  },
  {
    name: "v-5f19a21c",
    path: "/guide/redis-sentry.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5f19a21c").then(next)
    },
  },
  {
    name: "v-de38b564",
    path: "/guide/prepare.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-de38b564").then(next)
    },
  },
  {
    name: "v-b2b41b9e",
    path: "/guide/userManual/01-introduction.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-b2b41b9e").then(next)
    },
  },
  {
    name: "v-7e20cb1b",
    path: "/guide/userManual/02-login.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7e20cb1b").then(next)
    },
  },
  {
    name: "v-7213561b",
    path: "/guide/userManual/04-authority.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7213561b").then(next)
    },
  },
  {
    name: "v-0c98708a",
    path: "/guide/userManual/05-system-settings.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0c98708a").then(next)
    },
  },
  {
    name: "v-a4e44aca",
    path: "/guide/userManual/07-my-task.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-a4e44aca").then(next)
    },
  },
  {
    name: "v-5d24737f",
    path: "/guide/userManual/09-timed-task.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5d24737f").then(next)
    },
  },
  {
    name: "v-2e00af06",
    path: "/guide/deploy.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2e00af06").then(next)
    },
  },
  {
    name: "v-2565ec8a",
    path: "/guide/userManual/10-message.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2565ec8a").then(next)
    },
  },
  {
    name: "v-db287be4",
    path: "/miscellaneous/release-notes.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-db287be4").then(next)
    },
  },
  {
    name: "v-fb41d53a",
    path: "/zh/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-fb41d53a").then(next)
    },
  },
  {
    path: "/zh/index.html",
    redirect: "/zh/"
  },
  {
    name: "v-f8650914",
    path: "/zh/faq/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-f8650914").then(next)
    },
  },
  {
    path: "/zh/faq/index.html",
    redirect: "/zh/faq/"
  },
  {
    name: "v-0c63e776",
    path: "/zh/guide/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0c63e776").then(next)
    },
  },
  {
    path: "/zh/guide/index.html",
    redirect: "/zh/guide/"
  },
  {
    name: "v-9412f956",
    path: "/zh/guide/deploy.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-9412f956").then(next)
    },
  },
  {
    name: "v-df02e68a",
    path: "/zh/guide/prepare.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-df02e68a").then(next)
    },
  },
  {
    name: "v-5ef88155",
    path: "/zh/guide/redis-sentry.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5ef88155").then(next)
    },
  },
  {
    name: "v-d7bc48b0",
    path: "/zh/guide/userManual/01-introduction.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-d7bc48b0").then(next)
    },
  },
  {
    name: "v-2b07ebf8",
    path: "/zh/guide/userManual/02-login.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2b07ebf8").then(next)
    },
  },
  {
    name: "v-30f69388",
    path: "/zh/guide/userManual/03-organization.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-30f69388").then(next)
    },
  },
  {
    name: "v-a9745968",
    path: "/zh/guide/userManual/04-authority.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-a9745968").then(next)
    },
  },
  {
    name: "v-e66c8864",
    path: "/zh/guide/userManual/05-system-settings.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-e66c8864").then(next)
    },
  },
  {
    name: "v-a0dcf580",
    path: "/zh/guide/userManual/07-my-task.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-a0dcf580").then(next)
    },
  },
  {
    name: "v-a923a730",
    path: "/zh/guide/userManual/08-workflow.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-a923a730").then(next)
    },
  },
  {
    name: "v-51cd4408",
    path: "/zh/guide/userManual/09-timed-task.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-51cd4408").then(next)
    },
  },
  {
    name: "v-08e4cc8e",
    path: "/zh/guide/userManual/10-message.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-08e4cc8e").then(next)
    },
  },
  {
    name: "v-7d9c91e6",
    path: "/zh/guide/userManual/11-monitor.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7d9c91e6").then(next)
    },
  },
  {
    name: "v-46eab6af",
    path: "/zh/miscellaneous/release-notes.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-46eab6af").then(next)
    },
  },
  {
    name: "v-368b043b",
    path: "/guide/userManual/11-monitor.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-368b043b").then(next)
    },
  },
  {
    name: "v-51b4d8ce",
    path: "/guide/run.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-51b4d8ce").then(next)
    },
  },
  {
    name: "v-2d2e4dc3",
    path: "/guide/userManual/03-organization.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2d2e4dc3").then(next)
    },
  },
  {
    name: "v-502d2535",
    path: "/guide/userManual/08-workflow.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-502d2535").then(next)
    },
  },
  {
    name: "v-9c8cd422",
    path: "/guide/userManual/06-application-settings.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-9c8cd422").then(next)
    },
  },
  {
    name: "v-531b1e33",
    path: "/zh/guide/run.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-531b1e33").then(next)
    },
  },
  {
    name: "v-17609470",
    path: "/zh/guide/userManual/06-application-settings.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-17609470").then(next)
    },
  },
  {
    name: "v-65237f56",
    path: "/development/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-65237f56").then(next)
    },
  },
  {
    path: "/development/index.html",
    redirect: "/development/"
  },
  {
    name: "v-53b644d6",
    path: "/zh/development/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-53b644d6").then(next)
    },
  },
  {
    path: "/zh/development/index.html",
    redirect: "/zh/development/"
  },
  {
    path: '*',
    component: GlobalLayout
  }
]