/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "",
  "description": "",
  "base": "/uapsite/",
  "pages": [
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroImage": "/logo.png",
        "actionText": "Get Started Quickly →",
        "actionLink": "/guide/",
        "features": [
          {
            "title": "Platformization",
            "details": "Forming a development model based on HX UAP, each business system only needs to develop functions for actual business scenarios, without paying attention to the underlying platform issues."
          },
          {
            "title": "Modular",
            "details": "HX UAP itself also has modular features. During deployment and use, different models need only be deployed according to actual needs. Each functional model forms an independent service. Business systems developed based on HX UAP also have similar capabilities."
          },
          {
            "title": "Compatibility",
            "details": "The HX UAP platform is compatible with the underlying functions of existing business systems. The front end meets the overall interface style and operation mode, while also providing the operation mode and habits of the old system. The platform also provides various adaptations for retrofitting legacy systems."
          },
          {
            "title": "Ease of use",
            "details": "It meets the unified style of the interface design of the system software, and refers to the habits of various field users in the operation mode, so that the end user can get started quickly."
          }
        ],
        "footer": "Copyright © 2020-uap"
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-52f08e60",
      "path": "/",
      "lastUpdated": "3/13/2020, 4:23:35 PM"
    },
    {
      "title": "Introduction",
      "frontmatter": {},
      "regularPath": "/guide/",
      "relativePath": "guide/README.md",
      "key": "v-5989d1f3",
      "path": "/guide/",
      "headers": [
        {
          "level": 2,
          "title": "Background",
          "slug": "background"
        },
        {
          "level": 2,
          "title": "Product target",
          "slug": "product-target"
        },
        {
          "level": 2,
          "title": "Product range definition",
          "slug": "product-range-definition"
        },
        {
          "level": 2,
          "title": "Product value",
          "slug": "product-value"
        }
      ],
      "lastUpdated": "3/13/2020, 4:23:35 PM"
    },
    {
      "title": "Deploy",
      "frontmatter": {},
      "regularPath": "/guide/deploy.html",
      "relativePath": "guide/deploy.md",
      "key": "v-230bca34",
      "path": "/guide/deploy.html",
      "headers": [
        {
          "level": 2,
          "title": "Platform Basic Function Database",
          "slug": "platform-basic-function-database"
        },
        {
          "level": 2,
          "title": "Program",
          "slug": "program"
        }
      ],
      "lastUpdated": "3/13/2020, 4:23:35 PM"
    },
    {
      "title": "Preparation for deployment",
      "frontmatter": {},
      "regularPath": "/guide/prepare.html",
      "relativePath": "guide/prepare.md",
      "key": "v-18b1992e",
      "path": "/guide/prepare.html",
      "headers": [
        {
          "level": 2,
          "title": "Operating system",
          "slug": "operating-system"
        },
        {
          "level": 3,
          "title": "The unified application platform supports Windows server or Linux server. Linux server is recommended.",
          "slug": "the-unified-application-platform-supports-windows-server-or-linux-server-linux-server-is-recommended"
        },
        {
          "level": 3,
          "title": "Install operating system",
          "slug": "install-operating-system"
        },
        {
          "level": 2,
          "title": "Environmental preparation",
          "slug": "environmental-preparation"
        },
        {
          "level": 3,
          "title": "Unified application platform requires the following related tools or operating environment",
          "slug": "unified-application-platform-requires-the-following-related-tools-or-operating-environment"
        },
        {
          "level": 3,
          "title": "Install database",
          "slug": "install-database"
        },
        {
          "level": 3,
          "title": "Install JDK",
          "slug": "install-jdk"
        },
        {
          "level": 3,
          "title": "Install Tomcat",
          "slug": "install-tomcat"
        },
        {
          "level": 3,
          "title": "Install browser",
          "slug": "install-browser"
        },
        {
          "level": 3,
          "title": "Unified Application Platform Installation Package",
          "slug": "unified-application-platform-installation-package"
        }
      ],
      "lastUpdated": "3/13/2020, 4:23:35 PM"
    },
    {
      "title": "Introduction",
      "frontmatter": {
        "title": "Introduction",
        "metaTitle": "Introduction"
      },
      "regularPath": "/guide/userManual/01-introduction.html",
      "relativePath": "guide/userManual/01-introduction.md",
      "key": "v-8f8403de",
      "path": "/guide/userManual/01-introduction.html",
      "headers": [
        {
          "level": 2,
          "title": "Platform Introduction",
          "slug": "platform-introduction"
        },
        {
          "level": 2,
          "title": "The Term",
          "slug": "the-term"
        }
      ]
    },
    {
      "title": "redis configuration",
      "frontmatter": {},
      "regularPath": "/guide/redis-sentry.html",
      "relativePath": "guide/redis-sentry.md",
      "key": "v-19c9cad2",
      "path": "/guide/redis-sentry.html",
      "lastUpdated": "3/13/2020, 4:23:35 PM"
    },
    {
      "title": "Login and Home",
      "frontmatter": {
        "title": "Login and Home",
        "metaTitle": "Login and Home"
      },
      "regularPath": "/guide/userManual/02-login.html",
      "relativePath": "guide/userManual/02-login.md",
      "key": "v-32491efb",
      "path": "/guide/userManual/02-login.html",
      "headers": [
        {
          "level": 2,
          "title": "Log In",
          "slug": "log-in"
        },
        {
          "level": 2,
          "title": "Home",
          "slug": "home"
        }
      ]
    },
    {
      "title": "System Settings",
      "frontmatter": {
        "title": "System Settings",
        "metaTitle": "System settings",
        "sidebarDepth": 3
      },
      "regularPath": "/guide/userManual/05-system-settings.html",
      "relativePath": "guide/userManual/05-system-settings.md",
      "key": "v-b16928ca",
      "path": "/guide/userManual/05-system-settings.html",
      "headers": [
        {
          "level": 2,
          "title": "System coding",
          "slug": "system-coding"
        },
        {
          "level": 3,
          "title": "Add encoding",
          "slug": "add-encoding"
        },
        {
          "level": 3,
          "title": "Edit encoding",
          "slug": "edit-encoding"
        },
        {
          "level": 3,
          "title": "Delete encoding",
          "slug": "delete-encoding"
        },
        {
          "level": 2,
          "title": "API Interface Log",
          "slug": "api-interface-log"
        },
        {
          "level": 3,
          "title": "View detailed log information",
          "slug": "view-detailed-log-information"
        },
        {
          "level": 2,
          "title": "Login log",
          "slug": "login-log"
        },
        {
          "level": 2,
          "title": "Calendar management",
          "slug": "calendar-management"
        },
        {
          "level": 2,
          "title": "Illegal login log",
          "slug": "illegal-login-log"
        },
        {
          "level": 2,
          "title": "Menu log",
          "slug": "menu-log"
        }
      ]
    },
    {
      "title": "My Mission",
      "frontmatter": {
        "title": "My Mission",
        "metaTitle": "My mission",
        "sidebarDepth": 3
      },
      "regularPath": "/guide/userManual/07-my-task.html",
      "relativePath": "guide/userManual/07-my-task.md",
      "key": "v-a8ad830a",
      "path": "/guide/userManual/07-my-task.html",
      "headers": [
        {
          "level": 2,
          "title": "My task",
          "slug": "my-task-2"
        },
        {
          "level": 2,
          "title": "History Mission",
          "slug": "history-mission"
        },
        {
          "level": 2,
          "title": "My process instance",
          "slug": "my-process-instance"
        }
      ]
    },
    {
      "title": "Rights Management",
      "frontmatter": {
        "title": "Rights Management",
        "metaTitle": "Rights Management",
        "sidebarDepth": 3
      },
      "regularPath": "/guide/userManual/04-authority.html",
      "relativePath": "guide/userManual/04-authority.md",
      "key": "v-6a19c9fb",
      "path": "/guide/userManual/04-authority.html",
      "headers": [
        {
          "level": 2,
          "title": "Roles",
          "slug": "roles"
        },
        {
          "level": 3,
          "title": "Add character",
          "slug": "add-character"
        },
        {
          "level": 3,
          "title": "Delete role",
          "slug": "delete-role"
        },
        {
          "level": 3,
          "title": "Edit role",
          "slug": "edit-role"
        },
        {
          "level": 3,
          "title": "Start and stop roles",
          "slug": "start-and-stop-roles"
        },
        {
          "level": 3,
          "title": "Role Assignment Menu",
          "slug": "role-assignment-menu"
        },
        {
          "level": 3,
          "title": "Configuration (assigning roles to users)",
          "slug": "configuration-assigning-roles-to-users"
        }
      ]
    },
    {
      "title": "Timed Task",
      "frontmatter": {
        "title": "Timed Task",
        "metaTitle": "Timed Task",
        "sidebarDepth": 3
      },
      "regularPath": "/guide/userManual/09-timed-task.html",
      "relativePath": "guide/userManual/09-timed-task.md",
      "key": "v-6d5d6f5f",
      "path": "/guide/userManual/09-timed-task.html",
      "headers": [
        {
          "level": 2,
          "title": "Scheduled task configuration",
          "slug": "scheduled-task-configuration"
        },
        {
          "level": 2,
          "title": "Execution history",
          "slug": "execution-history"
        }
      ]
    },
    {
      "title": "Message Center",
      "frontmatter": {
        "title": "Message Center",
        "metaTitle": "Message Center",
        "sidebarDepth": 3
      },
      "regularPath": "/guide/userManual/10-message.html",
      "relativePath": "guide/userManual/10-message.md",
      "key": "v-292f24ca",
      "path": "/guide/userManual/10-message.html",
      "headers": [
        {
          "level": 2,
          "title": "User messages",
          "slug": "user-messages"
        },
        {
          "level": 2,
          "title": "All messages",
          "slug": "all-messages"
        },
        {
          "level": 2,
          "title": "Configure the color of the message type",
          "slug": "configure-the-color-of-the-message-type"
        }
      ]
    },
    {
      "title": "Monitoring",
      "frontmatter": {
        "title": "Monitoring",
        "metaTitle": "Monitoring",
        "sidebarDepth": 3
      },
      "regularPath": "/guide/userManual/11-monitor.html",
      "relativePath": "guide/userManual/11-monitor.md",
      "key": "v-34a6681b",
      "path": "/guide/userManual/11-monitor.html",
      "headers": [
        {
          "level": 2,
          "title": "Monitoring data",
          "slug": "monitoring-data"
        }
      ]
    },
    {
      "title": "Release Notes",
      "frontmatter": {
        "sidebar": "auto"
      },
      "regularPath": "/miscellaneous/release-notes.html",
      "relativePath": "miscellaneous/release-notes.md",
      "key": "v-def1b424",
      "path": "/miscellaneous/release-notes.html",
      "headers": [
        {
          "level": 2,
          "title": "Version: UAP 2.0.0.0",
          "slug": "version-uap-2-0-0-0"
        },
        {
          "level": 3,
          "title": "New Function",
          "slug": "new-function"
        },
        {
          "level": 3,
          "title": "Bug fixes and optimizations",
          "slug": "bug-fixes-and-optimizations"
        },
        {
          "level": 2,
          "title": "Version: UAP 1.3.0.0",
          "slug": "version-uap-1-3-0-0"
        },
        {
          "level": 3,
          "title": "New Function",
          "slug": "new-function-2"
        },
        {
          "level": 3,
          "title": "Bug fixes and optimizations",
          "slug": "bug-fixes-and-optimizations-2"
        },
        {
          "level": 2,
          "title": "Version: UAP 1.2.0.3",
          "slug": "version-uap-1-2-0-3"
        },
        {
          "level": 3,
          "title": "New Function",
          "slug": "new-function-3"
        },
        {
          "level": 3,
          "title": "Bug fixes and optimizations",
          "slug": "bug-fixes-and-optimizations-3"
        },
        {
          "level": 2,
          "title": "Version: UAP 1.1.0.2",
          "slug": "version-uap-1-1-0-2"
        },
        {
          "level": 3,
          "title": "New Function",
          "slug": "new-function-4"
        },
        {
          "level": 3,
          "title": "Bug fixes and optimizations",
          "slug": "bug-fixes-and-optimizations-4"
        }
      ],
      "lastUpdated": "3/13/2020, 4:23:35 PM"
    },
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroImage": "/logo.png",
        "actionText": "快速了解 →",
        "actionLink": "/zh/guide/",
        "features": [
          {
            "title": "平台化",
            "details": "形成以HX UAP为基础的开发模式，各个业务系统只需要针对实际业务场景进行功能开发，无需关注底层平台问题。"
          },
          {
            "title": "模块化",
            "details": "HX UAP本身内部也具备模块化特征，在部署和使用过程中，只需要根据实际需求进行不同模型的部署，各个功能模型形成独自的服务，基于HX UAP开发的业务系统也具备类似能力。"
          },
          {
            "title": "兼容性",
            "details": "HX UAP平台兼容现有业务系统的底层功能，前端满足总体界面风格以及操作模式，同时也提供了旧有系统的操作模式以及习惯。平台也提供了各种适配用于旧有系统改造。"
          },
          {
            "title": "易用性",
            "details": "满足系统软件的界面设计统一风格，操作模式上参考了各个现场用户习惯，使得最终用户快速上手。"
          }
        ],
        "footer": "Copyright © 2020-uap"
      },
      "regularPath": "/zh/",
      "relativePath": "zh/README.md",
      "key": "v-2a8ced83",
      "path": "/zh/",
      "lastUpdated": "2020-3-13 4:23:35 PM"
    },
    {
      "title": "FAQ",
      "frontmatter": {
        "sidebar": "auto"
      },
      "regularPath": "/zh/faq/",
      "relativePath": "zh/faq/README.md",
      "key": "v-159d98d4",
      "path": "/zh/faq/",
      "lastUpdated": "2020-3-13 4:23:35 PM"
    },
    {
      "title": "介绍",
      "frontmatter": {},
      "regularPath": "/zh/guide/",
      "relativePath": "zh/guide/README.md",
      "key": "v-36ee8f96",
      "path": "/zh/guide/",
      "headers": [
        {
          "level": 2,
          "title": "背景",
          "slug": "背景"
        },
        {
          "level": 2,
          "title": "产品目标",
          "slug": "产品目标"
        },
        {
          "level": 2,
          "title": "产品范围定义",
          "slug": "产品范围定义"
        },
        {
          "level": 2,
          "title": "产品价值",
          "slug": "产品价值"
        }
      ],
      "lastUpdated": "2020-3-13 4:23:35 PM"
    },
    {
      "title": "部署",
      "frontmatter": {},
      "regularPath": "/zh/guide/deploy.html",
      "relativePath": "zh/guide/deploy.md",
      "key": "v-0830f196",
      "path": "/zh/guide/deploy.html",
      "headers": [
        {
          "level": 2,
          "title": "平台基础功能数据库",
          "slug": "平台基础功能数据库"
        },
        {
          "level": 2,
          "title": "程序",
          "slug": "程序"
        }
      ],
      "lastUpdated": "2020-3-13 4:23:35 PM"
    },
    {
      "title": "部署前的准备工作",
      "frontmatter": {},
      "regularPath": "/zh/guide/prepare.html",
      "relativePath": "zh/guide/prepare.md",
      "key": "v-1e3e189b",
      "path": "/zh/guide/prepare.html",
      "headers": [
        {
          "level": 2,
          "title": "操作系统",
          "slug": "操作系统"
        },
        {
          "level": 3,
          "title": "统一应用平台支持Windows服务器或者Linux服务器，推荐使用Linux服务器。",
          "slug": "统一应用平台支持windows服务器或者linux服务器，推荐使用linux服务器。"
        },
        {
          "level": 3,
          "title": "安装操作系统",
          "slug": "安装操作系统"
        },
        {
          "level": 2,
          "title": "环境准备",
          "slug": "环境准备"
        },
        {
          "level": 3,
          "title": "统一应用平台需要用到以下相关工具或者运行环境",
          "slug": "统一应用平台需要用到以下相关工具或者运行环境"
        },
        {
          "level": 3,
          "title": "安装数据库",
          "slug": "安装数据库"
        },
        {
          "level": 3,
          "title": "安装JDK",
          "slug": "安装jdk"
        },
        {
          "level": 3,
          "title": "安装Tomcat",
          "slug": "安装tomcat"
        },
        {
          "level": 3,
          "title": "安装浏览器",
          "slug": "安装浏览器"
        },
        {
          "level": 3,
          "title": "统一应用平台安装包",
          "slug": "统一应用平台安装包"
        }
      ],
      "lastUpdated": "2020-3-13 4:23:35 PM"
    },
    {
      "title": "redis配置",
      "frontmatter": {},
      "regularPath": "/zh/guide/redis-sentry.html",
      "relativePath": "zh/guide/redis-sentry.md",
      "key": "v-7f22b535",
      "path": "/zh/guide/redis-sentry.html",
      "lastUpdated": "2020-3-13 4:23:35 PM"
    },
    {
      "title": "FAQ",
      "frontmatter": {
        "sidebar": "auto"
      },
      "regularPath": "/faq/",
      "relativePath": "faq/README.md",
      "key": "v-b7b49082",
      "path": "/faq/",
      "lastUpdated": "3/13/2020, 4:23:35 PM"
    },
    {
      "title": "登录和首页",
      "frontmatter": {
        "title": "登录和首页",
        "metaTitle": "登录和首页"
      },
      "regularPath": "/zh/guide/userManual/02-login.html",
      "relativePath": "zh/guide/userManual/02-login.md",
      "key": "v-61641438",
      "path": "/zh/guide/userManual/02-login.html",
      "headers": [
        {
          "level": 2,
          "title": "登录",
          "slug": "登录"
        },
        {
          "level": 2,
          "title": "首页",
          "slug": "首页"
        }
      ]
    },
    {
      "title": "组织管理",
      "frontmatter": {
        "title": "组织管理",
        "metaTitle": "组织管理",
        "sidebarDepth": 3
      },
      "regularPath": "/zh/guide/userManual/03-organization.html",
      "relativePath": "zh/guide/userManual/03-organization.md",
      "key": "v-42e39130",
      "path": "/zh/guide/userManual/03-organization.html",
      "headers": [
        {
          "level": 2,
          "title": "用户",
          "slug": "用户"
        },
        {
          "level": 3,
          "title": "用户操作列表介绍",
          "slug": "用户操作列表介绍"
        },
        {
          "level": 3,
          "title": "新增用户",
          "slug": "新增用户"
        },
        {
          "level": 3,
          "title": "编辑用户",
          "slug": "编辑用户"
        },
        {
          "level": 3,
          "title": "配置（给用户配置角色）",
          "slug": "配置（给用户配置角色）"
        },
        {
          "level": 3,
          "title": "配置管理单元",
          "slug": "配置管理单元"
        },
        {
          "level": 3,
          "title": "重置密码",
          "slug": "重置密码"
        },
        {
          "level": 3,
          "title": "密码修改记录",
          "slug": "密码修改记录"
        },
        {
          "level": 3,
          "title": "启停用户",
          "slug": "启停用户"
        },
        {
          "level": 2,
          "title": "组织",
          "slug": "组织"
        },
        {
          "level": 3,
          "title": "新增组织",
          "slug": "新增组织"
        },
        {
          "level": 3,
          "title": "编辑组织",
          "slug": "编辑组织"
        },
        {
          "level": 3,
          "title": "组织排序",
          "slug": "组织排序"
        },
        {
          "level": 3,
          "title": "启停组织",
          "slug": "启停组织"
        },
        {
          "level": 2,
          "title": "管理单位配置",
          "slug": "管理单位配置"
        },
        {
          "level": 3,
          "title": "新增用户分配组织",
          "slug": "新增用户分配组织"
        },
        {
          "level": 3,
          "title": "删除用户已分配组织",
          "slug": "删除用户已分配组织"
        }
      ]
    },
    {
      "title": "权限管理",
      "frontmatter": {
        "title": "权限管理",
        "metaTitle": "权限管理",
        "sidebarDepth": 3
      },
      "regularPath": "/zh/guide/userManual/04-authority.html",
      "relativePath": "zh/guide/userManual/04-authority.md",
      "key": "v-864441a8",
      "path": "/zh/guide/userManual/04-authority.html",
      "headers": [
        {
          "level": 2,
          "title": "角色",
          "slug": "角色"
        },
        {
          "level": 3,
          "title": "新增角色",
          "slug": "新增角色"
        },
        {
          "level": 3,
          "title": "删除角色",
          "slug": "删除角色"
        },
        {
          "level": 3,
          "title": "编辑角色",
          "slug": "编辑角色"
        },
        {
          "level": 3,
          "title": "启停角色",
          "slug": "启停角色"
        },
        {
          "level": 3,
          "title": "角色分配菜单",
          "slug": "角色分配菜单"
        },
        {
          "level": 3,
          "title": "配置（将角色分配给用户）",
          "slug": "配置（将角色分配给用户）"
        }
      ]
    },
    {
      "title": "系统设置",
      "frontmatter": {
        "title": "系统设置",
        "metaTitle": "系统设置",
        "sidebarDepth": 3
      },
      "regularPath": "/zh/guide/userManual/05-system-settings.html",
      "relativePath": "zh/guide/userManual/05-system-settings.md",
      "key": "v-4e4ef7ae",
      "path": "/zh/guide/userManual/05-system-settings.html",
      "headers": [
        {
          "level": 2,
          "title": "系统编码",
          "slug": "系统编码"
        },
        {
          "level": 3,
          "title": "新增编码",
          "slug": "新增编码"
        },
        {
          "level": 3,
          "title": "编辑编码",
          "slug": "编辑编码"
        },
        {
          "level": 3,
          "title": "删除编码",
          "slug": "删除编码"
        },
        {
          "level": 2,
          "title": "API接口日志",
          "slug": "api接口日志"
        },
        {
          "level": 3,
          "title": "查看详细的日志信息",
          "slug": "查看详细的日志信息"
        },
        {
          "level": 2,
          "title": "登录日志",
          "slug": "登录日志"
        },
        {
          "level": 2,
          "title": "日历管理",
          "slug": "日历管理"
        },
        {
          "level": 2,
          "title": "非法登录日志",
          "slug": "非法登录日志"
        },
        {
          "level": 2,
          "title": "菜单日志",
          "slug": "菜单日志"
        }
      ]
    },
    {
      "title": "我的任务",
      "frontmatter": {
        "title": "我的任务",
        "metaTitle": "我的任务",
        "sidebarDepth": 3
      },
      "regularPath": "/zh/guide/userManual/07-my-task.html",
      "relativePath": "zh/guide/userManual/07-my-task.md",
      "key": "v-806afdc0",
      "path": "/zh/guide/userManual/07-my-task.html",
      "headers": [
        {
          "level": 2,
          "title": "我的任务",
          "slug": "我的任务-2"
        },
        {
          "level": 2,
          "title": "历史任务",
          "slug": "历史任务"
        },
        {
          "level": 2,
          "title": "我的流程实例",
          "slug": "我的流程实例"
        }
      ]
    },
    {
      "title": "工作流",
      "frontmatter": {
        "title": "工作流",
        "metaTitle": "工作流",
        "sidebarDepth": 3
      },
      "regularPath": "/zh/guide/userManual/08-workflow.html",
      "relativePath": "zh/guide/userManual/08-workflow.md",
      "key": "v-dd509f70",
      "path": "/zh/guide/userManual/08-workflow.html",
      "headers": [
        {
          "level": 2,
          "title": "流程设计",
          "slug": "流程设计"
        },
        {
          "level": 3,
          "title": "流程分组",
          "slug": "流程分组"
        },
        {
          "level": 3,
          "title": "流程",
          "slug": "流程"
        },
        {
          "level": 2,
          "title": "部署流程",
          "slug": "部署流程"
        },
        {
          "level": 3,
          "title": "流程表单配置",
          "slug": "流程表单配置"
        },
        {
          "level": 3,
          "title": "部署信息查看",
          "slug": "部署信息查看"
        },
        {
          "level": 2,
          "title": "流程实例",
          "slug": "流程实例"
        },
        {
          "level": 2,
          "title": "流程任务",
          "slug": "流程任务"
        },
        {
          "level": 2,
          "title": "页面配置",
          "slug": "页面配置"
        },
        {
          "level": 3,
          "title": "字段组合",
          "slug": "字段组合"
        },
        {
          "level": 3,
          "title": "字段",
          "slug": "字段"
        },
        {
          "level": 2,
          "title": "动态字段管理",
          "slug": "动态字段管理"
        }
      ]
    },
    {
      "title": "定时任务",
      "frontmatter": {
        "title": "定时任务",
        "metaTitle": "定时任务",
        "sidebarDepth": 3
      },
      "regularPath": "/zh/guide/userManual/09-timed-task.html",
      "relativePath": "zh/guide/userManual/09-timed-task.md",
      "key": "v-5d91d7e8",
      "path": "/zh/guide/userManual/09-timed-task.html",
      "headers": [
        {
          "level": 2,
          "title": "定时任务配置",
          "slug": "定时任务配置"
        },
        {
          "level": 2,
          "title": "执行历史",
          "slug": "执行历史"
        }
      ]
    },
    {
      "title": "消息中心",
      "frontmatter": {
        "title": "消息中心",
        "metaTitle": "消息中心",
        "sidebarDepth": 3
      },
      "regularPath": "/zh/guide/userManual/10-message.html",
      "relativePath": "zh/guide/userManual/10-message.md",
      "key": "v-191dc86e",
      "path": "/zh/guide/userManual/10-message.html",
      "headers": [
        {
          "level": 2,
          "title": "用户消息",
          "slug": "用户消息"
        },
        {
          "level": 2,
          "title": "所有消息",
          "slug": "所有消息"
        },
        {
          "level": 2,
          "title": "配置消息类型的颜色",
          "slug": "配置消息类型的颜色"
        }
      ]
    },
    {
      "title": "监控",
      "frontmatter": {
        "title": "监控",
        "metaTitle": "监控",
        "sidebarDepth": 3
      },
      "regularPath": "/zh/guide/userManual/11-monitor.html",
      "relativePath": "zh/guide/userManual/11-monitor.md",
      "key": "v-e454e474",
      "path": "/zh/guide/userManual/11-monitor.html",
      "headers": [
        {
          "level": 2,
          "title": "监控数据",
          "slug": "监控数据"
        }
      ]
    },
    {
      "title": "发布说明",
      "frontmatter": {
        "sidebar": "auto"
      },
      "regularPath": "/zh/miscellaneous/release-notes.html",
      "relativePath": "zh/miscellaneous/release-notes.md",
      "key": "v-5723b28f",
      "path": "/zh/miscellaneous/release-notes.html",
      "headers": [
        {
          "level": 2,
          "title": "版本：UAP 2.0.0.0",
          "slug": "版本：uap-2-0-0-0"
        },
        {
          "level": 3,
          "title": "新功能",
          "slug": "新功能"
        },
        {
          "level": 3,
          "title": "问题修复和优化",
          "slug": "问题修复和优化"
        },
        {
          "level": 2,
          "title": "版本：UAP 1.3.0.0",
          "slug": "版本：uap-1-3-0-0"
        },
        {
          "level": 3,
          "title": "新功能",
          "slug": "新功能-2"
        },
        {
          "level": 3,
          "title": "问题修复和优化",
          "slug": "问题修复和优化-2"
        },
        {
          "level": 2,
          "title": "版本：UAP 1.2.0.3",
          "slug": "版本：uap-1-2-0-3"
        },
        {
          "level": 3,
          "title": "新功能",
          "slug": "新功能-3"
        },
        {
          "level": 3,
          "title": "问题修复和优化",
          "slug": "问题修复和优化-3"
        },
        {
          "level": 2,
          "title": "版本：UAP 1.1.0.2",
          "slug": "版本：uap-1-1-0-2"
        },
        {
          "level": 3,
          "title": "新功能",
          "slug": "新功能-4"
        },
        {
          "level": 3,
          "title": "问题修复和优化",
          "slug": "问题修复和优化-4"
        }
      ],
      "lastUpdated": "2020-3-13 4:23:35 PM"
    },
    {
      "title": "介绍",
      "frontmatter": {
        "title": "介绍",
        "metaTitle": "介绍"
      },
      "regularPath": "/zh/guide/userManual/01-introduction.html",
      "relativePath": "zh/guide/userManual/01-introduction.md",
      "key": "v-41b97f88",
      "path": "/zh/guide/userManual/01-introduction.html",
      "headers": [
        {
          "level": 2,
          "title": "平台介绍",
          "slug": "平台介绍"
        },
        {
          "level": 2,
          "title": "术语",
          "slug": "术语"
        }
      ]
    },
    {
      "title": "Configure and run",
      "frontmatter": {},
      "regularPath": "/guide/run.html",
      "relativePath": "guide/run.md",
      "key": "v-d5b6a6a4",
      "path": "/guide/run.html",
      "headers": [
        {
          "level": 2,
          "title": "Tomcat configuration",
          "slug": "tomcat-configuration"
        },
        {
          "level": 2,
          "title": "Configuration file",
          "slug": "configuration-file"
        },
        {
          "level": 3,
          "title": "The unified application platform release needs to be configured according to the actual needs of the environment",
          "slug": "the-unified-application-platform-release-needs-to-be-configured-according-to-the-actual-needs-of-the-environment"
        },
        {
          "level": 3,
          "title": "Each module has some specific configuration items, and the configuration of the module must be configured in advance when deploying each module",
          "slug": "each-module-has-some-specific-configuration-items-and-the-configuration-of-the-module-must-be-configured-in-advance-when-deploying-each-module"
        },
        {
          "level": 2,
          "title": "UAP front-end picture replacement",
          "slug": "uap-front-end-picture-replacement"
        },
        {
          "level": 2,
          "title": "Globalization",
          "slug": "globalization"
        },
        {
          "level": 2,
          "title": "Tomcat run and close",
          "slug": "tomcat-run-and-close"
        },
        {
          "level": 2,
          "title": "Lincense configuration",
          "slug": "lincense-configuration"
        },
        {
          "level": 2,
          "title": "System monitoring configuration",
          "slug": "system-monitoring-configuration"
        },
        {
          "level": 2,
          "title": "Open unified application platform",
          "slug": "open-unified-application-platform"
        }
      ],
      "lastUpdated": "3/13/2020, 4:23:35 PM"
    },
    {
      "title": "Application Settings",
      "frontmatter": {
        "title": "Application Settings",
        "metaTitle": "Application settings",
        "sidebarDepth": 3
      },
      "regularPath": "/guide/userManual/06-application-settings.html",
      "relativePath": "guide/userManual/06-application-settings.md",
      "key": "v-747de1cf",
      "path": "/guide/userManual/06-application-settings.html",
      "headers": [
        {
          "level": 2,
          "title": "Application",
          "slug": "application"
        },
        {
          "level": 3,
          "title": "New application",
          "slug": "new-application"
        },
        {
          "level": 3,
          "title": "Edit application",
          "slug": "edit-application"
        },
        {
          "level": 3,
          "title": "Delete application",
          "slug": "delete-application"
        },
        {
          "level": 3,
          "title": "Sync application (not available on this button platform)",
          "slug": "sync-application-not-available-on-this-button-platform"
        },
        {
          "level": 3,
          "title": "Start and stop applications",
          "slug": "start-and-stop-applications"
        },
        {
          "level": 2,
          "title": "Menu",
          "slug": "menu"
        },
        {
          "level": 3,
          "title": "New menu",
          "slug": "new-menu"
        },
        {
          "level": 3,
          "title": "Edit menu",
          "slug": "edit-menu"
        },
        {
          "level": 3,
          "title": "Delete menu",
          "slug": "delete-menu"
        },
        {
          "level": 2,
          "title": "Menu customization",
          "slug": "menu-customization"
        },
        {
          "level": 3,
          "title": "New menu customization",
          "slug": "new-menu-customization"
        },
        {
          "level": 3,
          "title": "Delete menu customization",
          "slug": "delete-menu-customization"
        },
        {
          "level": 2,
          "title": "API interface",
          "slug": "api-interface"
        },
        {
          "level": 3,
          "title": "New interface",
          "slug": "new-interface"
        },
        {
          "level": 3,
          "title": "Delete interface",
          "slug": "delete-interface"
        },
        {
          "level": 3,
          "title": "Editing excuses",
          "slug": "editing-excuses"
        },
        {
          "level": 3,
          "title": "View configuration menu",
          "slug": "view-configuration-menu"
        },
        {
          "level": 3,
          "title": "Start-stop interface",
          "slug": "start-stop-interface"
        },
        {
          "level": 2,
          "title": "Multitenancy",
          "slug": "multitenancy"
        },
        {
          "level": 3,
          "title": "Add tenant",
          "slug": "add-tenant"
        },
        {
          "level": 3,
          "title": "Delete tenant",
          "slug": "delete-tenant"
        },
        {
          "level": 3,
          "title": "Edit tenant",
          "slug": "edit-tenant"
        },
        {
          "level": 3,
          "title": "Flush the cache",
          "slug": "flush-the-cache"
        },
        {
          "level": 3,
          "title": "Personalized tenant configuration",
          "slug": "personalized-tenant-configuration"
        },
        {
          "level": 2,
          "title": "Tenant Information",
          "slug": "tenant-information"
        }
      ]
    },
    {
      "title": "Organization Management",
      "frontmatter": {
        "title": "Organization Management",
        "metaTitle": "Organization Management",
        "sidebarDepth": 3
      },
      "regularPath": "/guide/userManual/03-organization.html",
      "relativePath": "guide/userManual/03-organization.md",
      "key": "v-3ec659a3",
      "path": "/guide/userManual/03-organization.html",
      "headers": [
        {
          "level": 2,
          "title": "Users",
          "slug": "users"
        },
        {
          "level": 3,
          "title": "User operation list introduction",
          "slug": "user-operation-list-introduction"
        },
        {
          "level": 3,
          "title": "New users",
          "slug": "new-users"
        },
        {
          "level": 3,
          "title": "Edit user",
          "slug": "edit-user"
        },
        {
          "level": 3,
          "title": "Configure (configure roles for users)",
          "slug": "configure-configure-roles-for-users"
        },
        {
          "level": 3,
          "title": "Configuration snap-in",
          "slug": "configuration-snap-in"
        },
        {
          "level": 3,
          "title": "Reset Password",
          "slug": "reset-password"
        },
        {
          "level": 3,
          "title": "Password modification records",
          "slug": "password-modification-records"
        },
        {
          "level": 3,
          "title": "Start and stop users",
          "slug": "start-and-stop-users"
        },
        {
          "level": 2,
          "title": "Organization",
          "slug": "organization"
        },
        {
          "level": 3,
          "title": "Add organization",
          "slug": "add-organization"
        },
        {
          "level": 3,
          "title": "Edit organization",
          "slug": "edit-organization"
        },
        {
          "level": 3,
          "title": "Organization sort",
          "slug": "organization-sort"
        },
        {
          "level": 3,
          "title": "Start-stop organization",
          "slug": "start-stop-organization"
        },
        {
          "level": 2,
          "title": "Management unit configuration",
          "slug": "management-unit-configuration"
        },
        {
          "level": 3,
          "title": "Add User Assignment Organization",
          "slug": "add-user-assignment-organization"
        },
        {
          "level": 3,
          "title": "Delete user assigned organization",
          "slug": "delete-user-assigned-organization"
        }
      ]
    },
    {
      "title": "Workflow",
      "frontmatter": {
        "title": "Workflow",
        "metaTitle": "Workflow",
        "sidebarDepth": 3
      },
      "regularPath": "/guide/userManual/08-workflow.html",
      "relativePath": "guide/userManual/08-workflow.md",
      "key": "v-34ff1115",
      "path": "/guide/userManual/08-workflow.html",
      "headers": [
        {
          "level": 2,
          "title": "Process Design",
          "slug": "process-design"
        },
        {
          "level": 3,
          "title": "Process grouping",
          "slug": "process-grouping"
        },
        {
          "level": 3,
          "title": "Process",
          "slug": "process"
        },
        {
          "level": 2,
          "title": "Deployment process",
          "slug": "deployment-process"
        },
        {
          "level": 3,
          "title": "Process form configuration",
          "slug": "process-form-configuration"
        },
        {
          "level": 3,
          "title": "View deployment information",
          "slug": "view-deployment-information"
        },
        {
          "level": 2,
          "title": "Process instance",
          "slug": "process-instance"
        },
        {
          "level": 2,
          "title": "Process task",
          "slug": "process-task"
        },
        {
          "level": 2,
          "title": "Page configuration",
          "slug": "page-configuration"
        },
        {
          "level": 3,
          "title": "Field Combination",
          "slug": "field-combination"
        },
        {
          "level": 3,
          "title": "Field",
          "slug": "field"
        },
        {
          "level": 2,
          "title": "Dynamic field management",
          "slug": "dynamic-field-management"
        }
      ]
    },
    {
      "title": "配置和运行",
      "frontmatter": {},
      "regularPath": "/zh/guide/run.html",
      "relativePath": "zh/guide/run.md",
      "key": "v-13948a13",
      "path": "/zh/guide/run.html",
      "headers": [
        {
          "level": 2,
          "title": "tomcat配置",
          "slug": "tomcat配置"
        },
        {
          "level": 2,
          "title": "配置文件",
          "slug": "配置文件"
        },
        {
          "level": 3,
          "title": "统一应用平台发布需要根据实际需要环境配置",
          "slug": "统一应用平台发布需要根据实际需要环境配置"
        },
        {
          "level": 3,
          "title": "各个模块有一些特定的配置项，在部署每个模块时要提前配置好该模块的配置",
          "slug": "各个模块有一些特定的配置项，在部署每个模块时要提前配置好该模块的配置"
        },
        {
          "level": 2,
          "title": "UAP前端图片替换",
          "slug": "uap前端图片替换"
        },
        {
          "level": 2,
          "title": "国际化",
          "slug": "国际化"
        },
        {
          "level": 2,
          "title": "tomcat运行和关闭",
          "slug": "tomcat运行和关闭"
        },
        {
          "level": 2,
          "title": "lincense 配置",
          "slug": "lincense-配置"
        },
        {
          "level": 2,
          "title": "系统监控配置",
          "slug": "系统监控配置"
        },
        {
          "level": 2,
          "title": "打开统一应用平台",
          "slug": "打开统一应用平台"
        }
      ],
      "lastUpdated": "2020-3-13 4:23:35 PM"
    },
    {
      "title": "应用设置",
      "frontmatter": {
        "title": "应用设置",
        "metaTitle": "应用设置",
        "sidebarDepth": 3
      },
      "regularPath": "/zh/guide/userManual/06-application-settings.html",
      "relativePath": "zh/guide/userManual/06-application-settings.md",
      "key": "v-50e399a8",
      "path": "/zh/guide/userManual/06-application-settings.html",
      "headers": [
        {
          "level": 2,
          "title": "应用",
          "slug": "应用"
        },
        {
          "level": 3,
          "title": "新增应用",
          "slug": "新增应用"
        },
        {
          "level": 3,
          "title": "编辑应用",
          "slug": "编辑应用"
        },
        {
          "level": 3,
          "title": "删除应用",
          "slug": "删除应用"
        },
        {
          "level": 3,
          "title": "同步应用（这个按钮平台中没有）",
          "slug": "同步应用（这个按钮平台中没有）"
        },
        {
          "level": 3,
          "title": "启停应用",
          "slug": "启停应用"
        },
        {
          "level": 2,
          "title": "菜单",
          "slug": "菜单"
        },
        {
          "level": 3,
          "title": "新增菜单",
          "slug": "新增菜单"
        },
        {
          "level": 3,
          "title": "编辑菜单",
          "slug": "编辑菜单"
        },
        {
          "level": 3,
          "title": "删除菜单",
          "slug": "删除菜单"
        },
        {
          "level": 2,
          "title": "菜单定制",
          "slug": "菜单定制"
        },
        {
          "level": 3,
          "title": "新增菜单定制",
          "slug": "新增菜单定制"
        },
        {
          "level": 3,
          "title": "删除菜单定制",
          "slug": "删除菜单定制"
        },
        {
          "level": 2,
          "title": "API接口",
          "slug": "api接口"
        },
        {
          "level": 3,
          "title": "新增接口",
          "slug": "新增接口"
        },
        {
          "level": 3,
          "title": "删除接口",
          "slug": "删除接口"
        },
        {
          "level": 3,
          "title": "编辑借口",
          "slug": "编辑借口"
        },
        {
          "level": 3,
          "title": "查看配置菜单",
          "slug": "查看配置菜单"
        },
        {
          "level": 3,
          "title": "启停接口",
          "slug": "启停接口"
        },
        {
          "level": 2,
          "title": "多租户",
          "slug": "多租户"
        },
        {
          "level": 3,
          "title": "新增租户",
          "slug": "新增租户"
        },
        {
          "level": 3,
          "title": "删除租户",
          "slug": "删除租户"
        },
        {
          "level": 3,
          "title": "编辑租户",
          "slug": "编辑租户"
        },
        {
          "level": 3,
          "title": "刷新缓存",
          "slug": "刷新缓存"
        },
        {
          "level": 3,
          "title": "个性化配置租户",
          "slug": "个性化配置租户"
        },
        {
          "level": 2,
          "title": "租户信息",
          "slug": "租户信息"
        }
      ]
    }
  ],
  "themeConfig": {
    "logo": "/logo-head.png",
    "editLinks": true,
    "smoothScroll": true,
    "locales": {
      "/": {
        "label": "English",
        "selectText": "Languages",
        "ariaLabel": "Select language",
        "editLinkText": "Edit this page on GitHub",
        "lastUpdated": "Last Updated",
        "nav": [
          {
            "text": "Guide",
            "link": "/guide/"
          },
          {
            "text": "Learn more",
            "ariaLabel": "Learn more",
            "items": [
              {
                "text": "FAQ",
                "link": "/faq/"
              },
              {
                "text": "Release Notes",
                "link": "/miscellaneous/release-notes.html"
              }
            ]
          },
          {
            "text": "License Apply",
            "link": "https://172.16.45.18/ui/page/login.html"
          }
        ],
        "sidebar": {
          "/guide/": [
            {
              "title": "Guide",
              "collapsable": false,
              "children": [
                ""
              ]
            },
            {
              "title": "Deploy",
              "collapsable": false,
              "children": [
                "prepare",
                "deploy",
                "run",
                "redis-sentry"
              ]
            },
            {
              "title": "User Manuals",
              "collapsable": false,
              "children": [
                "userManual/01-introduction",
                "userManual/02-login",
                "userManual/03-organization",
                "userManual/04-authority",
                "userManual/05-system-settings",
                "userManual/06-application-settings",
                "userManual/07-my-task",
                "userManual/08-workflow",
                "userManual/09-timed-task",
                "userManual/10-message",
                "userManual/11-monitor"
              ]
            }
          ]
        }
      },
      "/zh/": {
        "label": "简体中文",
        "selectText": "选择语言",
        "ariaLabel": "选择语言",
        "editLinkText": "在 GitHub 上编辑此页",
        "lastUpdated": "上次更新",
        "nav": [
          {
            "text": "指南",
            "link": "/zh/guide/"
          },
          {
            "text": "了解更多",
            "ariaLabel": "了解更多",
            "items": [
              {
                "text": "常见问题",
                "link": "/zh/faq/"
              },
              {
                "text": "发布说明",
                "link": "/zh/miscellaneous/release-notes.html"
              }
            ]
          },
          {
            "text": "License 申请",
            "link": "https://172.16.45.18/ui/page/login.html"
          }
        ],
        "sidebar": {
          "/zh/guide/": [
            {
              "title": "指南",
              "collapsable": false,
              "children": [
                ""
              ]
            },
            {
              "title": "部署",
              "collapsable": false,
              "children": [
                "prepare",
                "deploy",
                "run",
                "redis-sentry"
              ]
            },
            {
              "title": "用户手册",
              "collapsable": false,
              "children": [
                "userManual/01-introduction",
                "userManual/02-login",
                "userManual/03-organization",
                "userManual/04-authority",
                "userManual/05-system-settings",
                "userManual/06-application-settings",
                "userManual/07-my-task",
                "userManual/08-workflow",
                "userManual/09-timed-task",
                "userManual/10-message",
                "userManual/11-monitor"
              ]
            }
          ]
        }
      }
    }
  },
  "locales": {
    "/": {
      "lang": "en-US",
      "title": "UAP Site",
      "description": "UAP usage help document",
      "path": "/"
    },
    "/zh/": {
      "lang": "zh-CN",
      "title": "UAP 文档",
      "description": "UAP使用帮助文档",
      "path": "/zh/"
    }
  }
}