/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "",
  "description": "",
  "base": "/uapsite/",
  "pages": [
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroImage": "/logo.png",
        "actionText": "Get Started Quickly →",
        "actionLink": "/guide/",
        "features": [
          {
            "title": "Platformization",
            "details": "Forming a development model based on HX UAP, each business system only needs to develop functions for actual business scenarios, without paying attention to the underlying platform issues."
          },
          {
            "title": "Modular",
            "details": "HX UAP itself also has modular features. During deployment and use, different models need only be deployed according to actual needs. Each functional model forms an independent service. Business systems developed based on HX UAP also have similar capabilities."
          },
          {
            "title": "Compatibility",
            "details": "The HX UAP platform is compatible with the underlying functions of existing business systems. The front end meets the overall interface style and operation mode, while also providing the operation mode and habits of the old system. The platform also provides various adaptations for retrofitting legacy systems."
          },
          {
            "title": "Ease of use",
            "details": "It meets the unified style of the interface design of the system software, and refers to the habits of various field users in the operation mode, so that the end user can get started quickly."
          }
        ],
        "footer": "Copyright © 2020-uap"
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-4413c380",
      "path": "/",
      "lastUpdated": "3/13/2020, 4:23:35 PM"
    },
    {
      "title": "Deploy",
      "frontmatter": {},
      "regularPath": "/guide/deploy.html",
      "relativePath": "guide/deploy.md",
      "key": "v-2e00af06",
      "path": "/guide/deploy.html",
      "headers": [
        {
          "level": 2,
          "title": "Platform Basic Function Database",
          "slug": "platform-basic-function-database"
        },
        {
          "level": 2,
          "title": "Program",
          "slug": "program"
        }
      ],
      "lastUpdated": "3/13/2020, 4:23:35 PM"
    },
    {
      "title": "redis configuration",
      "frontmatter": {},
      "regularPath": "/guide/redis-sentry.html",
      "relativePath": "guide/redis-sentry.md",
      "key": "v-5f19a21c",
      "path": "/guide/redis-sentry.html",
      "lastUpdated": "3/13/2020, 4:23:35 PM"
    },
    {
      "title": "Preparation for deployment",
      "frontmatter": {},
      "regularPath": "/guide/prepare.html",
      "relativePath": "guide/prepare.md",
      "key": "v-de38b564",
      "path": "/guide/prepare.html",
      "headers": [
        {
          "level": 2,
          "title": "Operating system",
          "slug": "operating-system"
        },
        {
          "level": 3,
          "title": "The unified application platform supports Windows server or Linux server. Linux server is recommended.",
          "slug": "the-unified-application-platform-supports-windows-server-or-linux-server-linux-server-is-recommended"
        },
        {
          "level": 3,
          "title": "Install operating system",
          "slug": "install-operating-system"
        },
        {
          "level": 2,
          "title": "Environmental preparation",
          "slug": "environmental-preparation"
        },
        {
          "level": 3,
          "title": "Unified application platform requires the following related tools or operating environment",
          "slug": "unified-application-platform-requires-the-following-related-tools-or-operating-environment"
        },
        {
          "level": 3,
          "title": "Install database",
          "slug": "install-database"
        },
        {
          "level": 3,
          "title": "Install JDK",
          "slug": "install-jdk"
        },
        {
          "level": 3,
          "title": "Install Tomcat",
          "slug": "install-tomcat"
        },
        {
          "level": 3,
          "title": "Install browser",
          "slug": "install-browser"
        },
        {
          "level": 3,
          "title": "Unified Application Platform Installation Package",
          "slug": "unified-application-platform-installation-package"
        }
      ],
      "lastUpdated": "3/13/2020, 4:23:35 PM"
    },
    {
      "title": "Login and Home",
      "frontmatter": {
        "title": "Login and Home",
        "metaTitle": "Login and Home"
      },
      "regularPath": "/guide/userManual/login.html",
      "relativePath": "guide/userManual/login.md",
      "key": "v-fbf75a2a",
      "path": "/guide/userManual/login.html",
      "headers": [
        {
          "level": 2,
          "title": "Log In",
          "slug": "log-in"
        },
        {
          "level": 2,
          "title": "Home",
          "slug": "home"
        }
      ],
      "lastUpdated": "3/13/2020, 4:23:35 PM"
    },
    {
      "title": "Introduction",
      "frontmatter": {
        "title": "Introduction",
        "metaTitle": "Introduction"
      },
      "regularPath": "/guide/userManual/introduction.html",
      "relativePath": "guide/userManual/introduction.md",
      "key": "v-2b64abca",
      "path": "/guide/userManual/introduction.html",
      "headers": [
        {
          "level": 2,
          "title": "Platform Introduction",
          "slug": "platform-introduction"
        },
        {
          "level": 2,
          "title": "The Term",
          "slug": "the-term"
        }
      ],
      "lastUpdated": "3/13/2020, 4:23:35 PM"
    },
    {
      "title": "Release Notes",
      "frontmatter": {
        "sidebar": "auto"
      },
      "regularPath": "/miscellaneous/release-notes.html",
      "relativePath": "miscellaneous/release-notes.md",
      "key": "v-db287be4",
      "path": "/miscellaneous/release-notes.html",
      "headers": [
        {
          "level": 2,
          "title": "Version: UAP 2.0.0.0",
          "slug": "version-uap-2-0-0-0"
        },
        {
          "level": 3,
          "title": "New Function",
          "slug": "new-function"
        },
        {
          "level": 3,
          "title": "Bug fixes and optimizations",
          "slug": "bug-fixes-and-optimizations"
        },
        {
          "level": 2,
          "title": "Version: UAP 1.3.0.0",
          "slug": "version-uap-1-3-0-0"
        },
        {
          "level": 3,
          "title": "New Function",
          "slug": "new-function-2"
        },
        {
          "level": 3,
          "title": "Bug fixes and optimizations",
          "slug": "bug-fixes-and-optimizations-2"
        },
        {
          "level": 2,
          "title": "Version: UAP 1.2.0.3",
          "slug": "version-uap-1-2-0-3"
        },
        {
          "level": 3,
          "title": "New Function",
          "slug": "new-function-3"
        },
        {
          "level": 3,
          "title": "Bug fixes and optimizations",
          "slug": "bug-fixes-and-optimizations-3"
        },
        {
          "level": 2,
          "title": "Version: UAP 1.1.0.2",
          "slug": "version-uap-1-1-0-2"
        },
        {
          "level": 3,
          "title": "New Function",
          "slug": "new-function-4"
        },
        {
          "level": 3,
          "title": "Bug fixes and optimizations",
          "slug": "bug-fixes-and-optimizations-4"
        }
      ],
      "lastUpdated": "3/13/2020, 4:23:35 PM"
    },
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroImage": "/logo.png",
        "actionText": "快速了解 →",
        "actionLink": "/zh/guide/",
        "features": [
          {
            "title": "平台化",
            "details": "形成以HX UAP为基础的开发模式，各个业务系统只需要针对实际业务场景进行功能开发，无需关注底层平台问题。"
          },
          {
            "title": "模块化",
            "details": "HX UAP本身内部也具备模块化特征，在部署和使用过程中，只需要根据实际需求进行不同模型的部署，各个功能模型形成独自的服务，基于HX UAP开发的业务系统也具备类似能力。"
          },
          {
            "title": "兼容性",
            "details": "HX UAP平台兼容现有业务系统的底层功能，前端满足总体界面风格以及操作模式，同时也提供了旧有系统的操作模式以及习惯。平台也提供了各种适配用于旧有系统改造。"
          },
          {
            "title": "易用性",
            "details": "满足系统软件的界面设计统一风格，操作模式上参考了各个现场用户习惯，使得最终用户快速上手。"
          }
        ],
        "footer": "Copyright © 2020-uap"
      },
      "regularPath": "/zh/",
      "relativePath": "zh/README.md",
      "key": "v-fb41d53a",
      "path": "/zh/",
      "lastUpdated": "2020-3-13 4:23:35 PM"
    },
    {
      "title": "FAQ",
      "frontmatter": {
        "sidebar": "auto"
      },
      "regularPath": "/zh/faq/",
      "relativePath": "zh/faq/README.md",
      "key": "v-f8650914",
      "path": "/zh/faq/",
      "headers": [
        {
          "level": 2,
          "title": "Why can’t palette.styl and index.styl merge into one API?",
          "slug": "why-can-t-palette-styl-and-index-styl-merge-into-one-api"
        },
        {
          "level": 2,
          "title": "What’s the differences between the clientDynamicModules and enhanceAppFiles?",
          "slug": "what-s-the-differences-between-the-clientdynamicmodules-and-enhanceappfiles"
        },
        {
          "level": 2,
          "title": "When do I need to use enhanceAppFiles?",
          "slug": "when-do-i-need-to-use-enhanceappfiles"
        },
        {
          "level": 2,
          "title": "When do I need to use clientDynamicModules?",
          "slug": "when-do-i-need-to-use-clientdynamicmodules"
        }
      ],
      "lastUpdated": "2020-3-13 4:23:35 PM"
    },
    {
      "title": "介绍",
      "frontmatter": {},
      "regularPath": "/zh/guide/",
      "relativePath": "zh/guide/README.md",
      "key": "v-0c63e776",
      "path": "/zh/guide/",
      "headers": [
        {
          "level": 2,
          "title": "背景",
          "slug": "背景"
        },
        {
          "level": 2,
          "title": "产品目标",
          "slug": "产品目标"
        },
        {
          "level": 2,
          "title": "产品范围定义",
          "slug": "产品范围定义"
        },
        {
          "level": 2,
          "title": "产品价值",
          "slug": "产品价值"
        }
      ],
      "lastUpdated": "2020-3-13 4:23:35 PM"
    },
    {
      "title": "FAQ",
      "frontmatter": {
        "sidebar": "auto"
      },
      "regularPath": "/faq/",
      "relativePath": "faq/README.md",
      "key": "v-500d679f",
      "path": "/faq/",
      "headers": [
        {
          "level": 2,
          "title": "Why can’t palette.styl and index.styl merge into one API?",
          "slug": "why-can-t-palette-styl-and-index-styl-merge-into-one-api"
        },
        {
          "level": 2,
          "title": "What’s the differences between the clientDynamicModules and enhanceAppFiles?",
          "slug": "what-s-the-differences-between-the-clientdynamicmodules-and-enhanceappfiles"
        },
        {
          "level": 2,
          "title": "When do I need to use enhanceAppFiles?",
          "slug": "when-do-i-need-to-use-enhanceappfiles"
        },
        {
          "level": 2,
          "title": "When do I need to use clientDynamicModules?",
          "slug": "when-do-i-need-to-use-clientdynamicmodules"
        }
      ],
      "lastUpdated": "3/13/2020, 4:23:35 PM"
    },
    {
      "title": "部署前的准备工作",
      "frontmatter": {},
      "regularPath": "/zh/guide/prepare.html",
      "relativePath": "zh/guide/prepare.md",
      "key": "v-df02e68a",
      "path": "/zh/guide/prepare.html",
      "headers": [
        {
          "level": 2,
          "title": "操作系统",
          "slug": "操作系统"
        },
        {
          "level": 3,
          "title": "统一应用平台支持Windows服务器或者Linux服务器，推荐使用Linux服务器。",
          "slug": "统一应用平台支持windows服务器或者linux服务器，推荐使用linux服务器。"
        },
        {
          "level": 3,
          "title": "安装操作系统",
          "slug": "安装操作系统"
        },
        {
          "level": 2,
          "title": "环境准备",
          "slug": "环境准备"
        },
        {
          "level": 3,
          "title": "统一应用平台需要用到以下相关工具或者运行环境",
          "slug": "统一应用平台需要用到以下相关工具或者运行环境"
        },
        {
          "level": 3,
          "title": "安装数据库",
          "slug": "安装数据库"
        },
        {
          "level": 3,
          "title": "安装JDK",
          "slug": "安装jdk"
        },
        {
          "level": 3,
          "title": "安装Tomcat",
          "slug": "安装tomcat"
        },
        {
          "level": 3,
          "title": "安装浏览器",
          "slug": "安装浏览器"
        },
        {
          "level": 3,
          "title": "统一应用平台安装包",
          "slug": "统一应用平台安装包"
        }
      ],
      "lastUpdated": "2020-3-13 4:23:35 PM"
    },
    {
      "title": "redis配置",
      "frontmatter": {},
      "regularPath": "/zh/guide/redis-sentry.html",
      "relativePath": "zh/guide/redis-sentry.md",
      "key": "v-5ef88155",
      "path": "/zh/guide/redis-sentry.html",
      "lastUpdated": "2020-3-13 4:23:35 PM"
    },
    {
      "title": "登录和首页",
      "frontmatter": {
        "title": "登录和首页",
        "metaTitle": "登录和首页"
      },
      "regularPath": "/zh/guide/userManual/login.html",
      "relativePath": "zh/guide/userManual/login.md",
      "key": "v-3a7998c8",
      "path": "/zh/guide/userManual/login.html",
      "headers": [
        {
          "level": 2,
          "title": "登录",
          "slug": "登录"
        },
        {
          "level": 2,
          "title": "首页",
          "slug": "首页"
        }
      ],
      "lastUpdated": "2020-3-13 4:23:35 PM"
    },
    {
      "title": "介绍",
      "frontmatter": {
        "title": "介绍",
        "metaTitle": "介绍"
      },
      "regularPath": "/zh/guide/userManual/introduction.html",
      "relativePath": "zh/guide/userManual/introduction.md",
      "key": "v-7151808c",
      "path": "/zh/guide/userManual/introduction.html",
      "headers": [
        {
          "level": 2,
          "title": "平台介绍",
          "slug": "平台介绍"
        },
        {
          "level": 2,
          "title": "术语",
          "slug": "术语"
        }
      ],
      "lastUpdated": "2020-3-13 4:23:35 PM"
    },
    {
      "title": "Introduction",
      "frontmatter": {},
      "regularPath": "/guide/",
      "relativePath": "guide/README.md",
      "key": "v-685691d3",
      "path": "/guide/",
      "headers": [
        {
          "level": 2,
          "title": "Background",
          "slug": "background"
        },
        {
          "level": 2,
          "title": "Product target",
          "slug": "product-target"
        },
        {
          "level": 2,
          "title": "Product range definition",
          "slug": "product-range-definition"
        },
        {
          "level": 2,
          "title": "Product value",
          "slug": "product-value"
        }
      ],
      "lastUpdated": "3/13/2020, 4:23:35 PM"
    },
    {
      "title": "发布说明",
      "frontmatter": {
        "sidebar": "auto"
      },
      "regularPath": "/zh/miscellaneous/release-notes.html",
      "relativePath": "zh/miscellaneous/release-notes.md",
      "key": "v-46eab6af",
      "path": "/zh/miscellaneous/release-notes.html",
      "headers": [
        {
          "level": 2,
          "title": "版本：UAP 2.0.0.0",
          "slug": "版本：uap-2-0-0-0"
        },
        {
          "level": 3,
          "title": "新功能",
          "slug": "新功能"
        },
        {
          "level": 3,
          "title": "问题修复和优化",
          "slug": "问题修复和优化"
        },
        {
          "level": 2,
          "title": "版本：UAP 1.3.0.0",
          "slug": "版本：uap-1-3-0-0"
        },
        {
          "level": 3,
          "title": "新功能",
          "slug": "新功能-2"
        },
        {
          "level": 3,
          "title": "问题修复和优化",
          "slug": "问题修复和优化-2"
        },
        {
          "level": 2,
          "title": "版本：UAP 1.2.0.3",
          "slug": "版本：uap-1-2-0-3"
        },
        {
          "level": 3,
          "title": "新功能",
          "slug": "新功能-3"
        },
        {
          "level": 3,
          "title": "问题修复和优化",
          "slug": "问题修复和优化-3"
        },
        {
          "level": 2,
          "title": "版本：UAP 1.1.0.2",
          "slug": "版本：uap-1-1-0-2"
        },
        {
          "level": 3,
          "title": "新功能",
          "slug": "新功能-4"
        },
        {
          "level": 3,
          "title": "问题修复和优化",
          "slug": "问题修复和优化-4"
        }
      ],
      "lastUpdated": "2020-3-13 4:23:35 PM"
    },
    {
      "title": "部署",
      "frontmatter": {},
      "regularPath": "/zh/guide/deploy.html",
      "relativePath": "zh/guide/deploy.md",
      "key": "v-9412f956",
      "path": "/zh/guide/deploy.html",
      "headers": [
        {
          "level": 2,
          "title": "平台基础功能数据库",
          "slug": "平台基础功能数据库"
        },
        {
          "level": 2,
          "title": "程序",
          "slug": "程序"
        }
      ],
      "lastUpdated": "2020-3-13 4:23:35 PM"
    },
    {
      "title": "Configure and run",
      "frontmatter": {},
      "regularPath": "/guide/run.html",
      "relativePath": "guide/run.md",
      "key": "v-51b4d8ce",
      "path": "/guide/run.html",
      "headers": [
        {
          "level": 2,
          "title": "Tomcat configuration",
          "slug": "tomcat-configuration"
        },
        {
          "level": 2,
          "title": "Configuration file",
          "slug": "configuration-file"
        },
        {
          "level": 3,
          "title": "The unified application platform release needs to be configured according to the actual needs of the environment",
          "slug": "the-unified-application-platform-release-needs-to-be-configured-according-to-the-actual-needs-of-the-environment"
        },
        {
          "level": 3,
          "title": "Each module has some specific configuration items, and the configuration of the module must be configured in advance when deploying each module",
          "slug": "each-module-has-some-specific-configuration-items-and-the-configuration-of-the-module-must-be-configured-in-advance-when-deploying-each-module"
        },
        {
          "level": 2,
          "title": "UAP front-end picture replacement",
          "slug": "uap-front-end-picture-replacement"
        },
        {
          "level": 2,
          "title": "Globalization",
          "slug": "globalization"
        },
        {
          "level": 2,
          "title": "Tomcat run and close",
          "slug": "tomcat-run-and-close"
        },
        {
          "level": 2,
          "title": "Lincense configuration",
          "slug": "lincense-configuration"
        },
        {
          "level": 2,
          "title": "System monitoring configuration",
          "slug": "system-monitoring-configuration"
        },
        {
          "level": 2,
          "title": "Open unified application platform",
          "slug": "open-unified-application-platform"
        }
      ],
      "lastUpdated": "3/13/2020, 4:23:35 PM"
    },
    {
      "title": "配置和运行",
      "frontmatter": {},
      "regularPath": "/zh/guide/run.html",
      "relativePath": "zh/guide/run.md",
      "key": "v-531b1e33",
      "path": "/zh/guide/run.html",
      "headers": [
        {
          "level": 2,
          "title": "tomcat配置",
          "slug": "tomcat配置"
        },
        {
          "level": 2,
          "title": "配置文件",
          "slug": "配置文件"
        },
        {
          "level": 3,
          "title": "统一应用平台发布需要根据实际需要环境配置",
          "slug": "统一应用平台发布需要根据实际需要环境配置"
        },
        {
          "level": 3,
          "title": "各个模块有一些特定的配置项，在部署每个模块时要提前配置好该模块的配置",
          "slug": "各个模块有一些特定的配置项，在部署每个模块时要提前配置好该模块的配置"
        },
        {
          "level": 2,
          "title": "UAP前端图片替换",
          "slug": "uap前端图片替换"
        },
        {
          "level": 2,
          "title": "国际化",
          "slug": "国际化"
        },
        {
          "level": 2,
          "title": "tomcat运行和关闭",
          "slug": "tomcat运行和关闭"
        },
        {
          "level": 2,
          "title": "lincense 配置",
          "slug": "lincense-配置"
        },
        {
          "level": 2,
          "title": "系统监控配置",
          "slug": "系统监控配置"
        },
        {
          "level": 2,
          "title": "打开统一应用平台",
          "slug": "打开统一应用平台"
        }
      ],
      "lastUpdated": "2020-3-13 4:23:35 PM"
    }
  ],
  "themeConfig": {
    "logo": "/logo-head.png",
    "repo": "wlpgdq/uapsite",
    "editLinks": true,
    "smoothScroll": true,
    "locales": {
      "/": {
        "label": "English",
        "selectText": "Languages",
        "ariaLabel": "Select language",
        "editLinkText": "Edit this page on GitHub",
        "lastUpdated": "Last Updated",
        "nav": [
          {
            "text": "Guide",
            "link": "/guide/"
          },
          {
            "text": "Learn more",
            "ariaLabel": "Learn more",
            "items": [
              {
                "text": "FAQ",
                "link": "/faq/"
              },
              {
                "text": "Release Notes",
                "link": "/miscellaneous/release-notes.html"
              }
            ]
          },
          {
            "text": "License Apply",
            "link": "https://172.16.45.18/ui/page/login.html"
          }
        ],
        "sidebar": {
          "/guide/": [
            {
              "title": "Guide",
              "collapsable": false,
              "children": [
                ""
              ]
            },
            {
              "title": "Deploy",
              "collapsable": false,
              "children": [
                "prepare",
                "deploy",
                "run",
                "redis-sentry"
              ]
            },
            {
              "title": "User Manuals",
              "collapsable": false,
              "children": [
                "userManual/introduction",
                "userManual/login"
              ]
            }
          ]
        }
      },
      "/zh/": {
        "label": "简体中文",
        "selectText": "选择语言",
        "ariaLabel": "选择语言",
        "editLinkText": "在 GitHub 上编辑此页",
        "lastUpdated": "上次更新",
        "nav": [
          {
            "text": "指南",
            "link": "/zh/guide/"
          },
          {
            "text": "了解更多",
            "ariaLabel": "了解更多",
            "items": [
              {
                "text": "常见问题",
                "link": "/zh/faq/"
              },
              {
                "text": "发布说明",
                "link": "/zh/miscellaneous/release-notes.html"
              }
            ]
          },
          {
            "text": "License 申请",
            "link": "https://172.16.45.18/ui/page/login.html"
          }
        ],
        "sidebar": {
          "/zh/guide/": [
            {
              "title": "指南",
              "collapsable": false,
              "children": [
                ""
              ]
            },
            {
              "title": "部署",
              "collapsable": false,
              "children": [
                "prepare",
                "deploy",
                "run",
                "redis-sentry"
              ]
            },
            {
              "title": "用户手册",
              "collapsable": false,
              "children": [
                "userManual/introduction",
                "userManual/login"
              ]
            }
          ]
        }
      }
    }
  },
  "locales": {
    "/": {
      "lang": "en-US",
      "title": "UAP Site",
      "description": "UAP usage help document",
      "path": "/"
    },
    "/zh/": {
      "lang": "zh-CN",
      "title": "UAP 文档",
      "description": "UAP使用帮助文档",
      "path": "/zh/"
    }
  }
}